server:
  port: 8080
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 112.74.72.92
    port: 6379
    timeout: 200000
    password: lovexzq13141314
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
    database: 0

  application:
    # 应用得名称
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruige?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: xzq1314
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\SS\